# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/GSGSolveitTest',
                'doc_host': 'https://gsgbills.github.io',
                'git_url': 'https://github.com/gsgbills/GSGSolveitTest',
                'lib_path': 'GSGSolveitTest'},
  'syms': {'GSGSolveitTest.core': {'GSGSolveitTest.core.foo': ('core.html#foo', 'GSGSolveitTest/core.py')}}}
